project:
  type: default
  render:
    - "*.dmd"
    - "*.md"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    filters:
      - datamd.lua
  pdf:
    documentclass: scrartcl
    filters:
      - datamd.lua

execute:
  enabled: true
  echo: false
  warning: false
  error: false
