name: DataMD CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-spa tesseract-ocr-fra
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter
        pip install pytest pytest-cov
    
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Test Python implementation
      run: |
        python python_implementation/process_dmd.py simple_example.dmd
        test -f simple_example.html
    
    - name: Test Quarto rendering
      run: |
        quarto render simple_example.dmd --to html
        test -f simple_example.html
    
    - name: Run tests
      run: |
        pytest tests/ --cov=python_implementation --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Lint with flake8
      run: |
        flake8 python_implementation/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 python_implementation/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check formatting with black
      run: black --check python_implementation/
    
    - name: Check import sorting with isort
      run: isort --check-only python_implementation/
